FROM node:22.12.0-bookworm-slim AS builder

ARG NEXT_PUBLIC_VERSION
ARG STAGING_PUBLIC_URL
ENV NEXT_PUBLIC_VERSION=${NEXT_PUBLIC_VERSION}
ENV MAIN_URL=${STAGING_PUBLIC_URL}
ENV FRONTEND_URL=${STAGING_PUBLIC_URL}
ENV NEXT_PUBLIC_BACKEND_URL=${STAGING_PUBLIC_URL}/api
ENV NODE_OPTIONS=--max-old-space-size=4096

RUN corepack enable && corepack prepare pnpm@10.6.1 --activate
WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm run build

FROM node:22.12.0-bookworm-slim AS runtime

ENV NODE_ENV=staging
ENV NODE_OPTIONS=--max-old-space-size=1024
RUN corepack enable && corepack prepare pnpm@10.6.1 --activate \
  && apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates \
  && rm -rf /var/lib/apt/lists/* \
  && mkdir -p /uploads \
  && chown node:node /uploads

WORKDIR /app
COPY --from=builder --chown=node:node /app /app
USER node

CMD ["pnpm", "start:prod:frontend"]
